#!/bin/bash

# Script to initialize ROCm for LLMs utilizing Ollama on CachyOS
# Supports: CachyOS (and other Arch-based distributions)

set -euo pipefail

ROCM_PATH="/opt/rocm"
ROCM_ENV_FILE="/etc/profile.d/rocm.sh"
RENDER_GROUP="render"
VIDEO_GROUP="video"

ROCM_PACKAGES=(
    rocm-opencl-runtime
    rocm-hip-runtime
    rocm-smi-lib
    rocm-device-libs
    hip-runtime-amd
    rocminfo
)

check_privileges() {
    if [ "$EUID" -ne 0 ] && [ "$(whoami)" != "root" ]; then
        echo "This script requires elevated privileges."
        echo "Please run with sudo."
        exit 1
    fi
}

detect_distribution() {
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        echo "${ID:-unknown}"
    else
        echo "unknown"
    fi
}

is_arch_based() {
    local distro="$1"
    case "$distro" in
        cachyos|arch|manjaro|endeavouros|garuda)
            return 0
            ;;
        *)
            return 1
            ;;
    esac
}

check_amd_gpu() {
    if ! lspci 2>/dev/null | grep -qi "amd\|radeon\|advanced micro"; then
        echo "Warning: No AMD GPU detected via lspci. ROCm requires an AMD GPU."
        read -p "Continue anyway? (y/N): " confirm
        if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
            echo "Aborted."
            exit 0
        fi
    else
        echo "AMD GPU detected:"
        lspci 2>/dev/null | grep -i "amd\|radeon\|advanced micro" | grep -i "vga\|display\|3d\|gpu" || \
            lspci 2>/dev/null | grep -i "radeon" || true
    fi
}

detect_gfx_version() {
    local gfx_version=""

    if command -v rocminfo &>/dev/null; then
        gfx_version=$(rocminfo 2>/dev/null | grep -oP 'gfx\d+' | head -1 || true)
    fi

    if [ -z "$gfx_version" ] && command -v lspci &>/dev/null; then
        local gpu_id
        gpu_id=$(lspci -nn 2>/dev/null | grep -i "amd\|radeon" | grep -i "vga\|display\|3d" | grep -oP '\[1002:[0-9a-f]+\]' | head -1 || true)

        case "$gpu_id" in
            *[67900-6910]*)  gfx_version="gfx1030" ;;
            *[73[0-9][0-9]]*)  gfx_version="gfx1100" ;;
        esac
    fi

    echo "$gfx_version"
}

install_rocm_packages() {
    echo ""
    echo "=== Installing ROCm Packages ==="

    if ! command -v pacman &>/dev/null; then
        echo "Error: pacman not found. This script requires an Arch-based distribution."
        exit 1
    fi

    echo "Updating package database..."
    pacman -Sy --noconfirm

    echo ""
    echo "Installing ROCm packages: ${ROCM_PACKAGES[*]}"
    pacman -S --noconfirm --needed "${ROCM_PACKAGES[@]}" || {
        echo ""
        echo "Some packages may not be in the standard repos."
        echo "Trying to install available packages individually..."
        for pkg in "${ROCM_PACKAGES[@]}"; do
            pacman -S --noconfirm --needed "$pkg" 2>/dev/null && \
                echo "  ✓ $pkg installed" || \
                echo "  ! $pkg not found in repos, skipping"
        done
    }

    echo ""
    echo "ROCm packages installed."
}

add_user_to_groups() {
    local target_user="${SUDO_USER:-}"

    if [ -z "$target_user" ]; then
        echo ""
        read -p "Enter the username to add to GPU groups (render/video): " target_user
        if [ -z "$target_user" ]; then
            echo "No user specified. Skipping group assignment."
            return
        fi
    fi

    echo ""
    echo "=== Configuring GPU Group Membership for '$target_user' ==="

    if ! id "$target_user" &>/dev/null; then
        echo "Error: User '$target_user' does not exist."
        return
    fi

    for group in "$RENDER_GROUP" "$VIDEO_GROUP"; do
        if getent group "$group" &>/dev/null; then
            if id -nG "$target_user" | grep -qw "$group"; then
                echo "  '$target_user' is already in group '$group'."
            else
                usermod -aG "$group" "$target_user"
                echo "  ✓ Added '$target_user' to group '$group'."
            fi
        else
            echo "  Warning: Group '$group' does not exist. Skipping."
        fi
    done

    echo ""
    echo "Note: Group changes take effect on next login."
}

configure_rocm_env() {
    echo ""
    echo "=== Configuring ROCm Environment Variables ==="

    local gfx_version
    gfx_version=$(detect_gfx_version)

    cat > "$ROCM_ENV_FILE" <<EOF
# ROCm environment configuration for Ollama LLM support
# Generated by setup_rocm_ollama_cachyos.sh

export ROCM_PATH="${ROCM_PATH}"
export HIP_PATH="${ROCM_PATH}"
export PATH="\${PATH}:${ROCM_PATH}/bin"
export LD_LIBRARY_PATH="\${LD_LIBRARY_PATH:-}:${ROCM_PATH}/lib:${ROCM_PATH}/lib64"
EOF

    if [ -n "$gfx_version" ]; then
        echo "" >> "$ROCM_ENV_FILE"
        echo "# Override GFX version for GPU compatibility (detected: ${gfx_version})" >> "$ROCM_ENV_FILE"
        echo "export HSA_OVERRIDE_GFX_VERSION=\"${gfx_version#gfx}\"" >> "$ROCM_ENV_FILE"
        echo "  ✓ HSA_OVERRIDE_GFX_VERSION set to '${gfx_version#gfx}' (detected GPU: $gfx_version)"
    else
        echo ""
        echo "Could not auto-detect GPU GFX version."
        echo "For unsupported GPUs, you may need to set HSA_OVERRIDE_GFX_VERSION manually."
        echo "  Common values:  1030 (RX 6000 series)  1100 (RX 7900 series)"
        echo "  Example: export HSA_OVERRIDE_GFX_VERSION=1030"
        read -p "Enter GFX version number (or press Enter to skip): " manual_gfx
        if [ -n "$manual_gfx" ]; then
            echo "" >> "$ROCM_ENV_FILE"
            echo "# Override GFX version for GPU compatibility" >> "$ROCM_ENV_FILE"
            echo "export HSA_OVERRIDE_GFX_VERSION=\"${manual_gfx}\"" >> "$ROCM_ENV_FILE"
            echo "  ✓ HSA_OVERRIDE_GFX_VERSION set to '${manual_gfx}'"
        fi
    fi

    chmod 644 "$ROCM_ENV_FILE"
    echo "  ✓ ROCm environment written to $ROCM_ENV_FILE"
}

install_ollama() {
    echo ""
    echo "=== Installing / Verifying Ollama ==="

    if command -v ollama &>/dev/null; then
        local ollama_ver
        ollama_ver=$(ollama --version 2>/dev/null || echo "unknown")
        echo "Ollama is already installed: $ollama_ver"
        return
    fi

    echo "Ollama not found. Attempting installation..."

    if pacman -Si ollama &>/dev/null; then
        pacman -S --noconfirm --needed ollama
        echo "  ✓ Ollama installed via pacman."
    elif command -v yay &>/dev/null; then
        sudo -u "${SUDO_USER:-root}" yay -S --noconfirm --needed ollama
        echo "  ✓ Ollama installed via yay (AUR)."
    elif command -v paru &>/dev/null; then
        sudo -u "${SUDO_USER:-root}" paru -S --noconfirm --needed ollama
        echo "  ✓ Ollama installed via paru (AUR)."
    else
        echo "Installing Ollama via official installer script..."
        curl -fsSL https://ollama.com/install.sh | sh
        echo "  ✓ Ollama installed via official installer."
    fi
}

configure_ollama_service() {
    echo ""
    echo "=== Configuring Ollama systemd Service ==="

    local service_dir="/etc/systemd/system/ollama.service.d"
    local override_file="${service_dir}/rocm.conf"

    mkdir -p "$service_dir"

    cat > "$override_file" <<EOF
# ROCm environment override for Ollama systemd service
# Generated by setup_rocm_ollama_cachyos.sh
[Service]
Environment="ROCM_PATH=${ROCM_PATH}"
Environment="HIP_PATH=${ROCM_PATH}"
EOF

    local gfx_line
    gfx_line=$(grep "HSA_OVERRIDE_GFX_VERSION" "$ROCM_ENV_FILE" 2>/dev/null | grep "^export" | head -1 || true)
    if [ -n "$gfx_line" ]; then
        local gfx_val
        gfx_val=$(echo "$gfx_line" | grep -oP '(?<=")[^"]+(?=")' || true)
        if [ -n "$gfx_val" ]; then
            echo "Environment=\"HSA_OVERRIDE_GFX_VERSION=${gfx_val}\"" >> "$override_file"
        fi
    fi

    chmod 644 "$override_file"
    echo "  ✓ Ollama service override written to $override_file"

    systemctl daemon-reload

    if systemctl is-enabled --quiet ollama 2>/dev/null; then
        echo "  Ollama service is already enabled."
    else
        systemctl enable ollama
        echo "  ✓ Ollama service enabled."
    fi

    if systemctl is-active --quiet ollama 2>/dev/null; then
        echo "  Restarting Ollama to apply ROCm configuration..."
        systemctl restart ollama
    else
        echo "  Starting Ollama service..."
        systemctl start ollama
    fi

    echo "  ✓ Ollama service is running."
}

verify_rocm() {
    echo ""
    echo "=== Verifying ROCm Installation ==="

    source "$ROCM_ENV_FILE" 2>/dev/null || true

    if command -v rocminfo &>/dev/null; then
        echo "rocminfo output:"
        echo "----------------"
        rocminfo 2>/dev/null | grep -E "Agent|Name|Marketing|gfx" | head -20 || \
            echo "  (No GPU agents found — reboot may be required)"
    else
        echo "  Warning: rocminfo not found. ROCm may not be fully installed."
    fi

    echo ""
    if command -v rocm-smi &>/dev/null; then
        echo "rocm-smi GPU status:"
        echo "--------------------"
        rocm-smi --showmeminfo vram 2>/dev/null || echo "  (rocm-smi could not read GPU info)"
    else
        echo "  Warning: rocm-smi not found."
    fi
}

print_summary() {
    echo ""
    echo "============================================"
    echo "  ROCm + Ollama Setup Complete"
    echo "============================================"
    echo ""
    echo "  ROCm packages:      installed"
    echo "  Environment file:   $ROCM_ENV_FILE"
    echo "  Ollama service:     enabled & running"
    echo ""
    echo "  Next steps:"
    echo "  1. Log out and back in (or reboot) for group changes to take effect."
    echo "  2. Source the ROCm environment in your current shell:"
    echo "       source $ROCM_ENV_FILE"
    echo "  3. Pull an LLM model and run it on the GPU:"
    echo "       ollama pull llama3"
    echo "       ollama run llama3"
    echo "  4. Verify GPU usage with:  rocm-smi --showutilization"
    echo ""
}

main() {
    echo ""
    echo "=== ROCm + Ollama Initialization for CachyOS ==="
    echo ""

    check_privileges

    local distro
    distro=$(detect_distribution)
    echo "Detected distribution: $distro"

    if ! is_arch_based "$distro"; then
        echo ""
        echo "Warning: This script is designed for CachyOS / Arch-based distributions."
        echo "Detected: $distro"
        read -p "Continue anyway? (y/N): " confirm
        if [ "$confirm" != "y" ] && [ "$confirm" != "Y" ]; then
            echo "Aborted."
            exit 0
        fi
    fi

    check_amd_gpu
    install_rocm_packages
    add_user_to_groups
    configure_rocm_env
    install_ollama
    configure_ollama_service
    verify_rocm
    print_summary
}

main "$@"
